### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by zjin-lcf** [ROCmSoftwarePlatform/MIOpenTensile#30]
Please advise how to install the software with the develop branch.  Thanks.

Environment
ROCM 4.5.2
gfx908

CXX=hipcc cmake ..

```
*******************************************************************************
*----------------------------------- ERROR -----------------------------------*
* The variable 'CMAKE_CXX_FLAGS' should only be set by the cmake toolchain,
* either by calling 'cmake -DCMAKE_CXX_FLAGS=" -std=c++14"' or
* set in a toolchain file and added with
* 'cmake -DCMAKE_TOOLCHAIN_FILE=<toolchain-file>'.
*-----------------------------------------------------------------------------*
*******************************************************************************

CMake Warning at /opt/rocm/share/rocm/cmake/ROCMChecks.cmake:41 (message):
  The toolchain variable 'CMAKE_CXX_FLAGS' is modified in the CMakeLists.txt.
Call Stack (most recent call first):
  build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/CMakeLists.txt:9999 (rocm_check_toolchain_var)
  build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/CMakeLists.txt:24 (set)


CMake Warning at build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/CMakeLists.txt:91 (find_package):
  By not providing "Findmsgpack.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "msgpack", but
  CMake did not find one.

  Could not find a package configuration file provided by "msgpack" with any
  of the following names:

    msgpackConfig.cmake
    msgpack-config.cmake

  Add the installation prefix of "msgpack" to CMAKE_PREFIX_PATH or set
  "msgpack_DIR" to a directory containing one of the above files.  If
  "msgpack" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at build/virtualenv/cmake/TensileConfig.cmake:125 (message):
  Unrecognized arguments: ON
Call Stack (most recent call first):
  CMakeLists.txt:92 (TensileCreateLibraryFiles)


-- Tensile script: /home/path/MIOpenTensile/build/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary
-- Tensile_CREATE_COMMAND: /home/path/MIOpenTensile/build/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary;--new-client-only;--no-legacy-components;--merge-files;--no-short-file-names;--no-library-print-debug;--code-object-version=V3;--cxx-compiler=hipcc;--architecture=all;--library-format=msgpack;/home/path/MIOpenTensile/yaml/asm_full;/home/path/MIOpenTensile/build/lib/miopentensile;HIP
-- Tensile_MANIFEST_FILE_PATH: /home/path/MIOpenTensile/build/lib/miopentensile/library/TensileManifest.txt
'/home/path/MIOpenTensile/build/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary' '--new-client-only' '--no-legacy-components' '--merge-files' '--no-short-file-names' '--no-library-print-debug' '--code-object-version=V3' '--cxx-compiler=hipcc' '--architecture=all' '--library-format=msgpack' '/home/path/MIOpenTensile/yaml/asm_full' '/home/path/MIOpenTensile/build/lib/miopentensile' 'HIP' '--generate-manifest-and-exit'
Traceback (most recent call last):
  File "/home/path/MIOpenTensile/build/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary", line 25, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
ModuleNotFoundError: No module named 'Tensile.TensileCreateLibrary'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/path/MIOpenTensile/build/virtualenv/lib/python3.8/site-packages/Tensile/bin/TensileCreateLibrary", line 32, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
ModuleNotFoundError: No module named 'Tensile.TensileCreateLibrary'
CMake Error at build/virtualenv/cmake/TensileConfig.cmake:227 (message):
  Error creating Tensile library: 1
Call Stack (most recent call first):
  CMakeLists.txt:92 (TensileCreateLibraryFiles)


-- Configuring incomplete, errors occurred!
See also "/home/path/MIOpenTensile/build/CMakeFiles/CMakeOutput.log".


```

**Comment by zjin-lcf** [comment]
Do you have some update ?

**Comment by junliume** [comment]
Hi @bragadeesh, it seems to be some tensile build issue. Could you please assign someone to take a look?
